### ISSUE TITLE
Make instructor emails clickable with a `mailto` link in courses page

### ISSUE THREAD

**Issue by jvoucsb** [ucsb-cs156-w21/proj-ucsb-cs-las#102]
# User Story

As a user I can click on an email in Courses table to starting writing an email to the address.

# Acceptance Criteria

- [x] The emails listed under Email section in Courses page is clickable
- [x] When clicking on the email, the user's mail client opens

# Implementation Todos

Front end:

- [x] Implement a `formatter` function to pass into Email columns for the CourseTable
- [x] Wrap email in a `<a>` tag with href attribute
- [x] Add `mailto:` to the beginning of the email to make it open the mail client

Back end:

None

Testing:

- [x]  All previous tests still pass

Guidance/Information:
- Changes should be in [`javascript/src/main/components/Courses/CourseTable.js`](https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las/blob/main/javascript/src/main/components/Courses/CourseTable.js)
- The app uses a library [BootstrapTableNext](https://react-bootstrap-table.github.io/react-bootstrap-table2/) for data tables
- More on formatter function for [BootstrapTableNext](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
- More on `mailto:` and specific [examples](https://en.wikipedia.org/wiki/Mailto)
- Specifically, the formatter function should accept `cell` parameter and should return JSX that is ``<a href=`mailto:${cell}`> { cell } </a>``
    - `cell` refers to the value of the cell in the column
    - the formatter function is applied to all cell values in the column (to change the format/display of the cell's data!)
    - Refer to the [priceFormatter](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) function
- Specifically, the formatter should be added in the [Instructor Emails column data](https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las/blob/5b0d91d28b16c0bd17894e162a98cddbd33f7fa9/javascript/src/main/components/Courses/CourseTable.js#L79)

**Comment by ethanmeade** [comment]
Created the branch "7pm-1-fixInstrMail" to handle this issue.

**Comment by ethanmeade** [comment]
Implementation is now in testing phase, fulfills requirements on mac through CSIL.

**Comment by ethanmeade** [comment]
Seems to work, will create pull request when pull requests are formally introduced.
