### ISSUE TITLE
On the page https://proj-ucsb-cs-las.herokuapp.com/tutorAssignments make the columns sortable.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-cs-las#113]
# User Story

As an instructor or admin, I can sort the Tutor Assignments table on any of the columns so that I can view the contents of the table more easily based on the columns I'm interested in.

# Acceptance Criteria

- [x] Each of the information columns (`id` , `Course`, `Tutor`, `Assignment Type`) in the Tutor Assignment tables has a clickable arrow that allows the user to sort the table rows in ascending or descending order based on that column's contents, like the Courses table. 

# Implementation Todos

Front end:
- [x] The Tutor Assignment table component `
proj-ucsb-cs-las/javascript/src/main/components/Courses/CourseTable.js ` should have sort carets, following the Courses table component as an example: `proj-ucsb-cs-las/javascript/src/main/components/TutorAssignment/TutorAssignmentTable.js`

Testing:

- [x]  All previous tests pass
- [x] A test should be added to `proj-ucsb-cs-las/javascript/src/test/components/TutorAssignment/TutorAssignmentTable.test.js ` checking that the sort carets are clickable and return the rows in the expected sorted order

**Comment by ethanmeade** [comment]
Created the branch "7pm-1-makeColumnSort" to handle the issue.
