### ISSUE TITLE
Create a drop-down menu for the day of the week when creating an office hour

### ISSUE THREAD

**Issue by JacquelineMai** [ucsb-cs156-w21/proj-ucsb-cs-las#114]
# User Story

As a tutor I can select the day of the week for my office hours from a drop-down menu so that all office hours use valid days of the week and a consistent format

# Acceptance Criteria

- [x] The user can select the day of the week for their office hour from a drop-down menu on the Office Hour create page
- [x] When a user selects a day, it is properly added to the Office Hour object that is created
...

# Implementation Todos

Front end:

- [x] The Day of the Week text field is changed to a drop-down menu with values "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
...

Back end:

- [ ] The day of the week is validated in the backend, to ensure it can only be one of the 7 menu values
...

Testing:

- [ ] All existing test pass, unless there is a test checking for a text field for the day of the week
      - If there is such a test, remove it
- [ ] There is a front-end test checking that there is a drop-down menu with the correct values on the Office Hour create page
- [ ] There are backend tests checking the validation of the day of the week field for the Office Hour model (one should try saving an object with an invalid day of week field and expect it to fail, and one should successfully save an object with a valid day of week) 
...

**Comment by carsoncoley** [comment]
branch name: 6pm-1-dropDownMenu
