### ISSUE TITLE
Office hour time should have validation on input and be standard time format (AM/PM)

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-w21/proj-ucsb-cs-las#115]
# User Story

As a admin I can add office hours in the specified format so that all the times are consistent.

# Acceptance Criteria

- [x] There is form validation when the admin hits submit for entering a new office hour to check that the office hour start and end time is in standard time format i.e. XX:XXPM ->  1:00PM, 4:00AM, 10:00PM...

# Implementation Todos

Front end:

- [x] If there is an incorrect time inputted, display field validation onto the office hours page describing what form input is malformed. This error would be based on what gets passed back from the backend.
Example from Course Tab
![image](https://user-images.githubusercontent.com/25646026/108791342-b2e3fd80-7533-11eb-9303-3671f82f7101.png)

Back end:

- [x] Backend endpoints should return an error if the time input is invalid.

Testing:

- [x] Add backend tests to test error cases of malformed times 
- [x] Front end test that checks for field validation is made when wrong input is passed into form
- [x] All previous tests pass

**Comment by LeoJr99** [comment]
Branch name: 6pm-1-officeHoursTimeFormat
