### ISSUE TITLE
Zoom link input should have validation to be a real zoom link 

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-w21/proj-ucsb-cs-las#116]
# User Story

As a admin I can get notified when I enter invalid zoom links for office hours so that I know that I entered malformed zoom links.

# Acceptance Criteria

- [ ] There is form validation when the admin hits submit for entering a new office hour to check that the zoom link  is valid (i. e. not a google.com link)

# Implementation Todos

Front end:

- [ ] If there is an incorrect zoom link inputted, display field validation onto the office hours page describing what form input is malformed. (like how the courses tab has) This error would be based on what gets passed back from the backend.
Example from Course Tab
![image](https://user-images.githubusercontent.com/25646026/108791342-b2e3fd80-7533-11eb-9303-3671f82f7101.png)

Back end:

- [ ]  Backend endpoints should return an error if the zoom link input is invalid. This will need to be done with some sort of regex or string checking.

Testing:

- [ ]  Add backend tests to test error case of malformed link
- [ ]  Front end test that a form input failed when wrong input is passed into form
- [ ]  All previous tests pass

**Comment by LeoJr99** [comment]
Quick note from 6pm-3. Make sure that during validation of zoom link that https:// is added to link before added to the database in order for it to be clickable from front end
