### ISSUE TITLE
Add CSV upload for course information (Admin only)

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-w21/proj-ucsb-cs-las#119]
# User Story

As a admin I can upload courses from a csv so that I don't have to type them all in on the /courses page(admin only).

# Acceptance Criteria

- [x] 'Upload CSV' button exists and only shows up for admins
- [x] 'Upload CSV' button correctly updates the courses page and database with courses based on the csv uploaded

# Implementation Todos

Front end:

- [x] 'Upload CSV' button exists and calls backend to do CSV uploading
- [x] If file is not a csv, show an error and description of error on the front end.

Back end:

- [x] Endpoints for CSV upload that correctly update course table with new courses that are parsed from CSV
- [x] Errors returned if file is not a CSV, if CSV is malformed, or any other issues.

Testing:

- [x] 'Upload CSV' button front end tests
- [x] Back end tests for uploading CSV endpoints
- [x] Back end tests for database getting updated with correct information
- [x] All previous tests pass

**Comment by jayleenli** [comment]
You can refer to proj-mapache-search of how they do their csv uploads

**Comment by peterbayerle** [comment]
> You can refer to proj-mapache-search of how they do their csv uploads

https://github.com/ucsb-cs156-w21/proj-mapache-search/pull/91/files
