### ISSUE TITLE
Admins that are not instructors should be able to see the Tutor's table

### ISSUE THREAD

**Issue by namabilly** [ucsb-cs156-w21/proj-ucsb-cs-las#141]
# Bug Report

Currently, Admins that are not instructors cannot see the Tutor's table.

# Steps to Reproduce

1.  Login as an admin that is not an instructor
2. Navigate to the Tutor's page (`/tutors`)

# Expected / Desired Behavior

You should be able to see a list of tutors below the Add Tutor Button.

# Observed / Actual Behavior

The Tutors table doesn't show up.

# Screenshots and Logs

What you should see:

![image](https://user-images.githubusercontent.com/1119017/110256419-ab6a1e80-7f4d-11eb-8914-a014c2bc1c4d.png)

What you see instead:

![image](https://user-images.githubusercontent.com/1119017/110256491-056ae400-7f4e-11eb-9a29-407bf6909946.png)

# Discussion

I could be wrong, but it may be that just fixing this line:

```
   {instructorTutorList && (
        <TutorTable
          tutors={tutorList}
          instructorTutors={instructorTutorList}
          admin={isAdmin}
          deleteTutor={deleteTutor}
        />
      )}
```

and changing `  {instructorTutorList && ( ` to `  { (isAdmin || instructorTutorList) && (` would fix it.

There is also a lot of weird code here ... why are we passing both `tutors` and `instructorTutorList` into this component?  Why are we asking the API for two different lists of tutors?

There is a lot of refactoring possible here that could be opportunities for this to be a higher point story if you can figure out what is going on, and how to simplify the code.

I think initially, the intention was that admins see ALL tutors, and instructors see only the tutors assigned to their classes.  But maybe we can simplify and just show all tutors to all instructors and all admins.  I think that might simplify things a lot.

**Comment by namabilly** [comment]
Seems like there is code for this. Bugs?

**Comment by pconrad** [comment]
I'm confused by this.

This page lists tutors, and provide a way to create, list, edit and delete tutors: 

https://proj-ucsb-cs-las.herokuapp.com/tutors

What new features would you add that are not already there?
