### ISSUE TITLE
Make tutors table sortable

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-cs-las#145]
# User Story

As an instructor or admin, I can sort the Tutor table on any of the columns so that I can view the contents of the table more easily based on the columns I'm interested in.

Similar to this PR: https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las/pull/139 but on the tutors table

# Discussion

The tutor's table currently looks like this:

![image](https://user-images.githubusercontent.com/1119017/110255562-3e548a00-7f49-11eb-9db6-2f5affa313b0.png)

But it isn't sortable the way TutorAssignments is.  Make it sortable like this:

![tutorAssignmentsSortable](https://user-images.githubusercontent.com/1119017/110255545-2f6dd780-7f49-11eb-96f1-39a432abb880.gif)

# Acceptance Criteria

- [x] Each of the information columns (`id` , `First Name`, `Last Name`, `Email`) in the Tutor Assignment tables has a clickable arrow that allows the user to sort the table rows in ascending or descending order based on that column's contents, like the Courses table.

**Comment by carsoncoley** [comment]
branch name: 6pm-1-tutorTableSortable
