### ISSUE TITLE
Fix quarter format W21 vs. 20211 on the quarter format selector  (10-20)

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-cs-las#150]
# User Story

As an admin, I can enter the quarter filter in QYY format (e.g. S21, F20) and it will work properly, so that I can set the current quarter in an intuitive way.

# Discussion

The quarter format selector works pretty well, but at the moment, it only works if you enter the quarter in the ugly 20211 format:

![image](https://user-images.githubusercontent.com/1119017/110380762-69a0ad00-800d-11eb-83e7-825eeafa889f.png)

But if you put in a human friendly quarter such as:

![image](https://user-images.githubusercontent.com/1119017/110380811-7cb37d00-800d-11eb-9e1e-8bece671ab45.png)

Then it does not work.

You could probably fix this either in the front end or the back end, and I can point you to some code for either solution .  But ht bottom line is that we want the quarter filter to be entered in W21, S21, etc. format and be displayed in that format.

What happens internally, is up to you.

# Code that might be helpful

* This file has utilities for manipulating quarters in the front end (e.g. converting between formats) https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las/blob/main/javascript/src/main/utils/quarter.ts

* This file has code for manipulating quarters in the backend.  It is currently a part of ucsb-courses-search, but you could copy that code into this repo.  https://github.com/ucsb-cs156-w21/proj-ucsb-courses-search/blob/main/src/main/java/edu/ucsb/courses/models/Quarter.java

Both of the files above have test code that goes along with them.

I estimate this story as between 10 and 20 points depending on how it is implemented.

**Comment by ethanmeade** [comment]
Issue is a duplicate, closing.
