### ISSUE TITLE
Tutor Assignment History (estimate 40 points)

### ISSUE THREAD

**Issue by matthewwong212** [ucsb-cs156-w21/proj-ucsb-cs-las#28]
As an admin, I can enter the name of a tutor and see a table of their entire history of service as a tutor.

# Acceptance Criteria

- [x] Be able to search for a tutor
- [x] See entire history of their service, as a table
- [x] Only accessible to Admins

# Implementation Todos

Front end:
 
- [x] There should be a link to a "Tutor Assignment History" page on the Admin drop-down menu
- [x] On the Tutor Assignment History page, there should be a drop-down menu that contains the names of all tutors in the database
- [x] When a tutor is selected, a table should be shown on the page listing every Tutor Assignment in the database for that tutor (including all courses and quarters)

Back end:

- [x] When a tutor is selected, search the database for all Tutor Assignments with that tutor
- [x] Return the data as a JSON object

Testing:

- [x] There is a front-end test checking that there is link to the "Tutor Assignment History" page on the Admin drop-down
- [x] There is a front end test checking that there is a drop-down on the Tutor History page that contains the names of the tutors
- [x] There is a front end testing that, when a tutor name is selected, there is a table present on the page containing the correct TutorAsssignments

**Comment by pconrad** [comment]
7pm-1-TutorAssignmentHistory
