### ISSUE TITLE
Courses table on main page should only show info for current quarter (2 points)

### ISSUE THREAD

**Issue by lukelewis66** [ucsb-cs156-w21/proj-ucsb-cs-las#32]
# User Story

As a user who is viewing the courses table, I can only see information for the current quarter so that I do not get confused by previous or future classes. 

# Acceptance Criteria

- [x] Courses table should only show info for the current quarter.
- [x] Info should include: Course ID, Course name, Current quarter, first name, last name, and email
...

# Implementation Todos

Front end:
- [x] The app automatically sends an API request for info when the main page renders.
- [x] The app receives and displays information for the current quarter.
...

Back end:
quarter = year and number (20204 - 4th quarter of 2020)
or F20
- [x] Create a config variable for the current quarter.
- [x] Check the config variable to determine relevant info to grab from the database.
- [x] Add an interface function to the courses repository to query for courses for the correct quarter. 
- [x] Extend the courses controller to include a current quarter endpoint for grabbing correct info. 
- [x] Return the information as an API response to the frontend. 
...

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage
...

**Comment by pconrad** [comment]
Done F20
