### ISSUE TITLE
The title of the app should be UCSB CS LAs, not "Demo CRA + Spring App"

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-cs-las#81]
# User Story

As a user I can see the name of the app in the title (i.e. the tab in my browser) so that I can easily find this app among my browser tabs.

That is, instead of seeing this:

![image](https://user-images.githubusercontent.com/1119017/101975395-188d4280-3bf1-11eb-9bf8-e2d078c6d04b.png)

I want to see the text "UCSB CS LAs" in place of "Demo CRA + Spring App"

# Acceptance Criteria

- [ ] I should see "UCSB CS LAs"  in place of "Demo CRA + Spring App" in the browser tab.

# Implementation Todos

Front end:

- [ ] In the file `javascript/public/index.html` change the title element to "UCSB CS LAs" 

Testing:

- [ ] Existing Front end tests pass and there is adequate coverage
- [ ] Add a test that loads the app and specifically looks for the title element on the page, checking that it contains "UCSB CS LAs"

**Comment by 96RadhikaJadhav** [comment]
@pconrad  Can I work on this issue?
