### ISSUE TITLE
Tutor Assignments page does not get tutor assignments correctly

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-w21/proj-ucsb-cs-las#85]
# User Story

As a instructor I can see the tutor assignments table and do operations on it so that I can create and edit tutor assignments.

# Acceptance Criteria

- [ ] Tutor assignments table displays as expected and has options to create, update, and delete assignments.

# Implementation Todos

Front end:

- [ ] Table on tutor assignments should display correctly
- [ ] Buttons for creating, updating, and deleting tutor assignments should be on the page

Back end:

- [ ] Endpoint that tutor assignments page calls to returns 404, this should be corrected. If the call is unsuccessful it should return some more descriptive error message
- [ ] Creating, updating, and deleting tutor assignments should correctly update the database based on the operation.

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
Seems to be fixed
