### ISSUE TITLE
Make Office Hours table rows alternate in color like Admin Panel table

### ISSUE THREAD

**Issue by JacquelineMai** [ucsb-cs156-w21/proj-ucsb-cs-las#94]
# User Story

As a user I can alternating color rows in the Office hours table, so that it is easier to differentiate between consecutive rows

# Acceptance Criteria

- [x] The office hours table should have alternate-color rows

# Implementation Todos

Front end:

- [x] Add  `striped={true}` on the `<BootstrapTable>`  open tag in the component that implements this table (following https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#striped-bool )

Testing:

- All previous tests still pass

**Comment by carsoncoley** [comment]
Branch name: 6pm-1-officeHoursTable

**Comment by carsoncoley** [comment]
Added 'striped={true}' to OfficeHourTable.js and committed the changes to the branch.
