### ISSUE TITLE
Add margin below "New Office Hour" Button

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-w21/proj-ucsb-cs-las#95]
# User Story

As a user I can see space between the "New Office Hour" button on the /officehours page so that I can see the difference between the button and table

# Acceptance Criteria

- [x] There is a margin of space between the "New Office Hour" button and the office hour table

# Implementation Todos

Front end:

- [x] Add a `marginBottom: "1rem"` to the `style` property for the "New Office Hours" button

Back end:

None

Testing:

- [x] All previous tests still pass

Guidance/Information:
- Changes should be in [`javascript/src/main/pages/Home/Home.js`](https://github.com/ucsb-cs156-w21/proj-ucsb-courses-search/blob/66e9ff8b601ec856091c4ad0bc825bd8c40e36a0/javascript/src/main/pages/Home/Home.js#L42)
- Check more on inline styling [here](https://reactjs.org/docs/dom-elements.html#style)

**Comment by moisesgtz** [comment]
new branch name: 6pm-1-newMarginNewOfficeHourButton
