### ISSUE TITLE
Update footer with better description and more relevant information

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-w21/proj-ucsb-cs-las#96]
# User Story

As a user I can see the correct app description from the footer so I don't have to figure out what the app is about.

# Discussion

Currently, the footer on the app has this appearance:

![image](https://user-images.githubusercontent.com/1119017/108132761-47e48380-7068-11eb-8cd1-7275b1831622.png)

This is left over from the template repo used to create the app.   Instead it should say something like:

> This app is a class project of [CMPSC 156](https://ucsb-cs156.github.io) at [UCSB](https://ucsb.edu).  Check out the source code [on GitHub](https://github.com/ucsb-cs156-w21/proj-mapache-search)!

Note that the links in the replacement text go to the correct places.

# Acceptance Criteria

- [ ] Footer should have a more accurate description about the app
- [ ] Footer should link to the correct GitHub repo ( https://github.com/ucsb-cs156-w21/proj-mapache-search )
- [ ] CMPSC 156 should link to https://ucsb-cs156.github.io
- [ ] UCSB should link to https://ucsb.edu

# Implementation Todos

Front end:

- [ ] Change text and links in footer (in `javascript/src/main/components/Footer/AppFooter.js`) 

# Testing:

See testing hints below

- [ ]  A new test is added to cover the UI change
- [ ]  All previous tests still pass

# Testing Hints

In file: `javascript/src/test/components/Footer/AppFooter.test.js`

This test will make sure that the indicated words appear and that they link to the correct places

```
 test("Links are correct", async () => {
    const { getByText } = render(<AppFooter />);
    expect(getByText('CMPSC 156').closest('a')).toHaveAttribute('href', 'https://ucsb-cs156.github.io')
    expect(getByText('UCSB').closest('a')).toHaveAttribute('href', 'https://ucsb.edu')
    expect(getByText('GitHub').closest('a')).toHaveAttribute('href', 'https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las)
  });
```

**Comment by Bryanz2019** [comment]
Branch Name: 6pm-3-updateFooter
